server:
  port: 4559

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  config:
    import: "optional:configtree:/mnt/secrets/hmc/"
  application:
    name: HMC HMI Inbound Adapter
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  main:
    allow-bean-definition-overriding: true
  cache:
    cache-names: hmcAccessTokenCache
    caffeine:
      spec: expireAfterWrite=1800s

hmc:
  cft-hearing-service:
    host: ${CFT_HEARING_SERVICE_URL:http://localhost:4561}

idam:
  api:
    url: ${IDAM_API_URL:http://localhost:5000}
  client:
    id: hmc_hmi_inbound_adapter
    secret: ${IDAM_CLIENT_SECRET:hmc_hmi_inbound_adapter_secret}
    scope: openid roles profile manage-user
    # same for all environments - not used in mca but configured as idam mandates for token generation
    redirect_uri: https://hmi-inbound-adapter/oauth2redirect
  s2s-auth:
    microservice: hmc_hmi_inbound_adapter
    totp_secret: ${IDAM_KEY_HMI_INBOUND_ADAPTER:AAAAAAAAAAAAAAAA}
    url: ${S2S_URL:http://localhost:4502}
  s2s-authorised:
    services: ${HMI_INBOUND_ADAPTER_S2S_AUTHORISED_SERVICES:api_gw}
  system-user:
    id: ${HMC_SYSTEM_USER_ID:master.caseworker@gmail.com}
    password: ${HMC_SYSTEM_USER_PASSWORD:Pa55word11}

azure:
  application-insights:
    instrumentation-key: ${hmc.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}
jms:
  servicebus:
    connection-string: ${HMC_SERVICE_BUS_CONNECTION_STRING}
    queue-name: ${HMC_SERVICE_BUS_QUEUE}
