server:
  port: 4559

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  config:
    import: "optional:configtree:/mnt/secrets/hmc/"
  application:
    name: HMC HMI Inbound Adapter
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  main:
    allow-bean-definition-overriding: true

hmc:
  cft-hearing-service:
    host: ${CFT_HEARING_SERVICE_URL:http://localhost:4561}

idam:
  s2s-auth:
    microservice: hmc_hmi_inbound_adapter
    totp_secret: ${IDAM_KEY_HMI_INBOUND_ADAPTER:AAAAAAAAAAAAAAAA}
    url: ${S2S_URL:http://localhost:4502}
  s2s-authorised:
    services: ${HMI_INBOUND_ADAPTER_S2S_AUTHORISED_SERVICES:api_gw}

azure:
  application-insights:
    instrumentation-key: ${hmc.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}
jms:
  servicebus:
    connection-string: ${HMC_SERVICE_BUS_CONNECTION_STRING}
    queue-name: ${HMC_SERVICE_BUS_QUEUE}
