apiVersion: v2
appVersion: "1.0"
description: A Helm chart for hmc-hmi-inbound-adapter App
name: hmc-hmi-inbound-adapter
home: https://github.com/hmcts/hmc-hmi-inbound-adapter
version: 0.0.5
maintainers:
  - name: HMCTS CCD Dev Team
dependencies:
  - name: java
    version: 3.6.0
    repository: '@hmctspublic'
  - name: servicebus
    version: 0.3.0
    repository: '@hmctspublic'
    condition: servicebus.enabled
