apiVersion: v2
appVersion: "1.0"
description: A Helm chart for hmc-hmi-inbound-adapter App
name: hmc-hmi-inbound-adapter
home: https://github.com/hmcts/hmc-hmi-inbound-adapter
version: 0.1.8
maintainers:
  - name: HMCTS CCD Dev Team
dependencies:
  - name: java
    version: 4.0.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
  - name: servicebus
    version: 0.4.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: servicebus.enabled
